#!/usr/bin/env python3
"""
convert_to_mif.py
=================
Converts any image (JPG, PNG, TIFF, BMP) into Quartus MIF format
for loading into FPGA Block RAM (image_rom.vhd).

Usage:
    python convert_to_mif.py input_image.jpg output.mif

Requirements:
    pip install Pillow

Output:
    MIF file with 320x240 pixels, 24-bit RGB (8R 8G 8B)
    Total: 76,800 words x 24 bits
"""

from PIL import Image
import sys
import os


def convert_to_mif(src_path, dst_path, width=320, height=240):
    """Convert image file to Quartus MIF format."""

    if not os.path.exists(src_path):
        print(f"Error: Input file not found: {src_path}")
        sys.exit(1)

    print(f"Opening image: {src_path}")
    img = Image.open(src_path).convert('RGB')
    original_size = img.size
    print(f"Original size: {original_size[0]} x {original_size[1]}")

    # Resize to target resolution
    img = img.resize((width, height), Image.LANCZOS)
    print(f"Resized to: {width} x {height}")

    total_pixels = width * height
    print(f"Total pixels: {total_pixels}")

    with open(dst_path, 'w') as f:
        # MIF header
        f.write(f'-- Quartus MIF generated by convert_to_mif.py\n')
        f.write(f'-- Source: {os.path.basename(src_path)}\n')
        f.write(f'-- Size: {width} x {height} = {total_pixels} pixels\n')
        f.write(f'-- Format: 24-bit RGB (8R 8G 8B)\n')
        f.write(f'\n')
        f.write(f'DEPTH = {total_pixels};\n')
        f.write(f'WIDTH = 24;\n')
        f.write(f'ADDRESS_RADIX = HEX;\n')
        f.write(f'DATA_RADIX = HEX;\n')
        f.write(f'CONTENT BEGIN\n')

        addr = 0
        for y in range(height):
            for x in range(width):
                r, g, b = img.getpixel((x, y))
                val = (r << 16) | (g << 8) | b
                f.write(f'    {addr:05X} : {val:06X};\n')
                addr += 1

        f.write('END;\n')

    file_size = os.path.getsize(dst_path) / 1024
    print(f"Done! Written to: {dst_path}")
    print(f"File size: {file_size:.1f} KB")


def main():
    if len(sys.argv) != 3:
        print("Usage: python convert_to_mif.py input_image output.mif")
        print("")
        print("Supported formats: JPG, PNG, TIFF, BMP")
        print("Output: 320x240 pixels, 24-bit RGB MIF file")
        sys.exit(1)

    src = sys.argv[1]
    dst = sys.argv[2]
    convert_to_mif(src, dst)


if __name__ == "__main__":
    main()
